version: '3.9'
services:
  postgres:
    image: postgres:11.21-alpine3.17
    container_name: my-postgres-container
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    networks:
      - myapp-net

  rabbitmq:
    image: rabbitmq:3.12.6-management-alpine
    container_name: my-rabbitmq-container
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - myapp-net

  myapp:
    build: .
    container_name: my-golang-app-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      MYAPP_DB_HOST: $MYAPP_DB_HOST
      MYAPP_DB_PORT: $MYAPP_DB_PORT
      MYAPP_DB_USER: $MYAPP_DB_USER
      MYAPP_DB_PASSWORD: $MYAPP_DB_PASSWORD
      MYAPP_DB_NAME: $MYAPP_DB_NAME
      MYAPP_RABBITMQ_HOST: $MYAPP_RABBITMQ_HOST
      MYAPP_RABBITMQ_PORT: $MYAPP_DB_PORT
      MYAPP_RABBITMQ_USER: $MYAPP_RABBITMQ_USER
      MYAPP_RABBITMQ_PASSWORD: $MYAPP_RABBITMQ_PASSWORD
    networks:
      - myapp-net

networks:
  myapp-net:
